/** @type {import('tailwindcss').Config} */
const defaultTheme = require('tailwindcss/defaultTheme');
export default {
	darkMode: ['class'],
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
	safelist: ['light', 'dark'],
	theme: {
		extend: {
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 4px)',
				sm: 'calc(var(--radius) - 12px)',
				xs: 'calc(var(--radius) - 16px)',
				xss: 'calc(var(--radius) - 20px)',
			},
			colors: {
				primary: {
					lighter: '#E3ECFF',
					light: '#99BBFF',
					main: '#1563FF',
					dark: '#024BDD',
					darker: '#053CAA',
					transparent8: 'hsl(from var(--primary-main) h s l / 8%)',
					transparent12: 'hsl(from var(--primary-main) h s l / 12%)',
					transparent16: 'hsl(from var(--primary-main) h s l / 16%)',
					transparent20: 'hsl(from var(--primary-main) h s l / 20%)',
					transparent24: 'hsl(from var(--primary-main) h s l / 24%)',
					transparent32: 'hsl(from var(--primary-main) h s l / 32%)',
					transparent48: 'hsl(from var(--primary-main) h s l / 48%)',
					gradientMain: 'linear-gradient(135deg, #1563FF 0%, #0D44B4 100%)',
					gradientBold: 'linear-gradient(135deg, #024BDD 0%, #053CAA 100%)',
				},
				secondary: {
					lighter: '#EFD6FF',
					light: '#C684FF',
					main: '#8E33FF',
					dark: '#5119B7',
					darker: '#27097A',
					transparent8: 'hsl(from var(--secondary-main) h s l / 8%)',
					transparent12: 'hsl(from var(--secondary-main) h s l / 12%)',
					transparent16: 'hsl(from var(--secondary-main) h s l / 16%)',
					transparent20: 'hsl(from var(--secondary-main) h s l / 20%)',
					transparent24: 'hsl(from var(--secondary-main) h s l / 24%)',
					transparent32: 'hsl(from var(--secondary-main) h s l / 32%)',
					transparent48: 'hsl(from var(--secondary-main) h s l / 48%)',
					gradientMain: 'linear-gradient(135deg, #C684FF 0%, #8E33FF 100%)',
					gradientBold: 'linear-gradient(135deg, #8E33FF 0%, #5119B7 100%)',
				},
				info: {
					lighter: '#CAFDF5',
					light: '#61F3F3',
					main: '#00B8D9',
					dark: '#006C9C',
					darker:'#003768',
					transparent8: 'hsl(from var(--info-main) h s l / 8%)',
					transparent12: 'hsl(from var(--info-main) h s l / 12%)',
					transparent16: 'hsl(from var(--info-main) h s l / 16%)',
					transparent20: 'hsl(from var(--info-main) h s l / 20%)',
					transparent24: 'hsl(from var(--info-main) h s l / 24%)',
					transparent32: 'hsl(from var(--info-main) h s l / 32%)',
					transparent48: 'hsl(from var(--info-main) h s l / 48%)',
					gradientMain: 'linear-gradient(135deg, #61F3F3 0%, #00B8D9 100%)',
					gradientBold: 'linear-gradient(135deg, #00B8D9 0%, #006C9C 100%)',
				},
				success: {
					lighter: '#D3FCD2',
					light: '#77ED8B',
					main: '#22C55E',
					dark: '#118D57',
					darker: '#065E49',
					transparent8: 'hsl(from var(--success-main) h s l / 8%)',
					transparent12: 'hsl(from var(--success-main) h s l / 12%)',
					transparent16: 'hsl(from var(--success-main) h s l / 16%)',
					transparent20: 'hsl(from var(--success-main) h s l / 20%)',
					transparent24: 'hsl(from var(--success-main) h s l / 24%)',
					transparent32: 'hsl(from var(--success-main) h s l / 32%)',
					transparent48: 'hsl(from var(--success-main) h s l / 48%)',
					gradientMain: 'linear-gradient(135deg, #77ED8B 0%, #22C55E 100%)',
					gradientBold: 'linear-gradient(135deg, #22C55E 0%, #118D57 100%)',
				},
				warning: {
					light: '#FFF5CC',
					lighter: '#FFD666',
					main: '#FFAB00',
					dark: '#B76E00',
					darker: '#7A4100',
					transparent8: 'hsl(from var(--warning-main) h s l / 8%)',
					transparent12: 'hsl(from var(--warning-main) h s l / 12%)',
					transparent16: 'hsl(from var(--warning-main) h s l / 16%)',
					transparent20: 'hsl(from var(--warning-main) h s l / 20%)',
					transparent24: 'hsl(from var(--warning-main) h s l / 24%)',
					transparent32: 'hsl(from var(--warning-main) h s l / 32%)',
					transparent48: 'hsl(from var(--warning-main) h s l / 48%)',
					gradientMain: 'linear-gradient(135deg, #FFD666 0%, #FFAB00 100%)',
					gradientBold: 'linear-gradient(135deg, #FFAB00 0%, #B76E00 100%)',
				},
				error: {
					light: '#FFE9D5',
					lighter: '#FFAC82',
					main: '#FF5630',
					dark: '#B71D18',
					darker: '#7A0916',
					transparent8: 'hsl(from var(--error-main) h s l / 8%)',
					transparent12: 'hsl(from var(--error-main) h s l / 12%)',
					transparent16: 'hsl(from var(--error-main) h s l / 16%)',
					transparent20: 'hsl(from var(--error-main) h s l / 20%)',
					transparent24: 'hsl(from var(--error-main) h s l / 24%)',
					transparent32: 'hsl(from var(--error-main) h s l / 32%)',
					transparent48: 'hsl(from var(--error-main) h s l / 48%)',
					gradientMain: 'linear-gradient(135deg, #FFAC82 0%, #FF5630 100%)',
					gradientBold: 'linear-gradient(135deg, #FF5630 0%, #B71D18 100%)',
				},
				grey: {
					'100': '#F9FAFB',
					'200': '#F4F6F8',
					'300': '#DFE3E8',
					'400': '#C4CDD5',
					'500': '#919EAB',
					'600': '#637381',
					'700': '#454F5B',
					'800': '#212B36',
					'900': '#161C24',
					transparent8: 'hsl(from var(--grey-500) h s l / 8%)',
					transparent12: 'hsl(from var(--grey-500) h s l / 12%)',
					transparent16: 'hsl(from var(--grey-500) h s l / 16%)',
					transparent24: 'hsl(from var(--grey-500) h s l / 24%)',
					transparent32: 'hsl(from var(--grey-500) h s l / 32%)',
					transparent48: 'hsl(from var(--grey-500) h s l / 48%)',
				},
				common: {
					black: '#000000',
					blackTransparent8: 'hsl(from var(--common-black) h s l / 8%)',
					blackTransparent12: 'hsl(from var(--common-black) h s l / 12%)',
					blackTransparent16: 'hsl(from var(--common-black) h s l / 16%)',
					blackTransparent24: 'hsl(from var(--common-black) h s l / 24%)',
					blackTransparent32: 'hsl(from var(--common-black) h s l / 32%)',
					blackTransparent48: 'hsl(from var(--common-black) h s l / 48%)',
					white: '#FFFFFF',
					whiteTransparent8: 'hsl(from var(--common-white) h s l / 8%)',
					whiteTransparent12: 'hsl(from var(--common-white) h s l / 12%)',
					whiteTransparent16: 'hsl(from var(--common-white) h s l / 16%)',
					whiteTransparent24: 'hsl(from var(--common-white) h s l / 24%)',
					whiteTransparent32: 'hsl(from var(--common-white) h s l / 32%)',
					whiteTransparent48: 'hsl(from var(--common-white) h s l / 48%)',
				},
			},
			fontFamily: {
				sans: ['NunitoSans', ...defaultTheme.fontFamily.sans],
			},
		},
	},
	plugins: [require('tailwindcss-animate')],
};
