/** @type {import('tailwindcss').Config} */
const defaultTheme = require('tailwindcss/defaultTheme');
export default {
	darkMode: ['class'],
	content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
	safelist: ['light', 'dark'],
	theme: {
		extend: {
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 4px)',
				sm: 'calc(var(--radius) - 12px)',
				xs: 'calc(var(--radius) - 16px)',
				xss: 'calc(var(--radius) - 20px)',
			},
			colors: {
				primary: {
					lighter: 'hsl(var(--primary-lighter))',
					light: 'hsl(var(--primary-light))',
					main: 'hsl(var(--primary-main))',
					dark: 'hsl(var(--primary-dark))',
					darker: 'hsl(var(--primary-darker))',
					transparent8: 'hsl(var(--primary-main)/ 8%)',
					transparent12: 'hsl(var(--primary-main)/ 12%)',
					transparent16: 'hsl(var(--primary-main)/ 16%)',
					transparent20: 'hsl(var(--primary-main)/ 20%)',
					transparent24: 'hsl(var(--primary-main)/ 24%)',
					transparent32: 'hsl(var(--primary-main)/ 32%)',
					transparent48: 'hsl(var(--primary-main)/ 48%)',
					gradientMain: 'linear-gradient(135deg, var(--primary-main) 0%, var(--primary-gradientMain) 100%)',
					gradientBold: 'linear-gradient(135deg, var(--primary-dark) 0%, var(--primary-darker) 100%)',
				},
				secondary: {
					lighter: 'hsl(var(--secondary-lighter))',
					light: 'hsl(var(--secondary-light))',
					main: 'hsl(var(--secondary-main))',
					dark: 'hsl(var(--secondary-dark))',
					darker: 'hsl(var(--secondary-darker))',
					transparent8: 'hsl(var(--secondary-main)/ 8%)',
					transparent12: 'hsl(var(--secondary-main)/ 12%)',
					transparent16: 'hsl(var(--secondary-main)/ 16%)',
					transparent20: 'hsl(var(--secondary-main)/ 20%)',
					transparent24: 'hsl(var(--secondary-main)/ 24%)',
					transparent32: 'hsl(var(--secondary-main)/ 32%)',
					transparent48: 'hsl(var(--secondary-main)/ 48%)',
					gradientMain: 'linear-gradient(135deg, var(--secondary-light) 0%, var(--secondary-main) 100%)',
					gradientBold: 'linear-gradient(135deg, var(--secondary-main) 0%, var(--secondary-dark) 100%)',
				},
				info: {
					lighter: 'hsl(var(--info-lighter))',
					light: 'hsl(var(--info-light))',
					main: 'hsl(var(--info-main))',
					dark: 'hsl(var(--info-dark))',
					darker: 'hsl(var(--info-darker))',
					transparent8: 'hsl(var(--info-main)/ 8%)',
					transparent12: 'hsl(var(--info-main)/ 12%)',
					transparent16: 'hsl(var(--info-main)/ 16%)',
					transparent20: 'hsl(var(--info-main)/ 20%)',
					transparent24: 'hsl(var(--info-main)/ 24%)',
					transparent32: 'hsl(var(--info-main)/ 32%)',
					transparent48: 'hsl(var(--info-main)/ 48%)',
					gradientMain: 'linear-gradient(135deg, var(--info-light) 0%, var(--info-main) 100%)',
					gradientBold: 'linear-gradient(135deg, var(--info-main) 0%, var(--info-dark) 100%)',
				},
				success: {
					lighter: 'hsl(var(--success-lighter))',
					light: 'hsl(var(--success-light))',
					main: 'hsl(var(--success-main))',
					dark: 'hsl(var(--success-dark))',
					darker: 'hsl(var(--success-darker))',
					transparent8: 'hsl(var(--success-main)/ 8%)',
					transparent12: 'hsl(var(--success-main)/ 12%)',
					transparent16: 'hsl(var(--success-main)/ 16%)',
					transparent20: 'hsl(var(--success-main)/ 20%)',
					transparent24: 'hsl(var(--success-main)/ 24%)',
					transparent32: 'hsl(var(--success-main)/ 32%)',
					transparent48: 'hsl(var(--success-main)/ 48%)',
					gradientMain: 'linear-gradient(135deg, var(--success-light) 0%, var(--success-main) 100%)',
					gradientBold: 'linear-gradient(135deg, var(--success-main) 0%, var(--success-dark) 100%)',
				},
				warning: {
					lighter: 'hsl(var(--warning-lighter))',
					light: 'hsl(var(--warning-light))',
					main: 'hsl(var(--warning-main))',
					dark: 'hsl(var(--warning-dark))',
					darker: 'hsl(var(--warning-darker))',
					transparent8: 'hsl(var(--warning-main)/ 8%)',
					transparent12: 'hsl(var(--warning-main)/ 12%)',
					transparent16: 'hsl(var(--warning-main)/ 16%)',
					transparent20: 'hsl(var(--warning-main)/ 20%)',
					transparent24: 'hsl(var(--warning-main)/ 24%)',
					transparent32: 'hsl(var(--warning-main)/ 32%)',
					transparent48: 'hsl(var(--warning-main)/ 48%)',
					gradientMain: 'linear-gradient(135deg, var(--warning-lighter) 0%, var(--warning-main) 100%)',
					gradientBold: 'linear-gradient(135deg, var(--warning-main) 0%, var(--warning-dark) 100%)',
				},
				error: {
					lighter: 'hsl(var(--error-lighter))',
					light: 'hsl(var(--error-light))',
					main: 'hsl(var(--error-main))',
					dark: 'hsl(var(--error-dark))',
					darker: 'hsl(var(--error-darker))',
					transparent8: 'hsl(var(--error-main)/ 8%)',
					transparent12: 'hsl(var(--error-main)/ 12%)',
					transparent16: 'hsl(var(--error-main)/ 16%)',
					transparent20: 'hsl(var(--error-main)/ 20%)',
					transparent24: 'hsl(var(--error-main)/ 24%)',
					transparent32: 'hsl(var(--error-main)/ 32%)',
					transparent48: 'hsl(var(--error-main)/ 48%)',
					gradientMain: 'linear-gradient(135deg, var(--error-light) 0%, var(--error-main) 100%)',
					gradientBold: 'linear-gradient(135deg, var(--error-main) 0%, var(--error-dark) 100%)',
				},
				grey: {
					'100': 'hsl(var(--grey-100))',
					'200': 'hsl(var(--grey-200))',
					'300': 'hsl(var(--grey-300))',
					'400': 'hsl(var(--grey-400))',
					'500': 'hsl(var(--grey-500))',
					'600': 'hsl(var(--grey-600))',
					'700': 'hsl(var(--grey-700))',
					'800': 'hsl(var(--grey-800))',
					'900': 'hsl(var(--grey-900))',
					transparent8: 'hsl(var(--grey-500)/ 8%)',
					transparent12: 'hsl(var(--grey-500)/ 12%)',
					transparent16: 'hsl(var(--grey-500)/ 16%)',
					transparent24: 'hsl(var(--grey-500)/ 24%)',
					transparent32: 'hsl(var(--grey-500)/ 32%)',
					transparent48: 'hsl(var(--grey-500)/ 48%)',
				},
				common: {
					black: 'hsl(var(--common-black))',
					blackTransparent8: 'hsl(var(--common-black)/ 8%)',
					blackTransparent12: 'hsl(var(--common-black)/ 12%)',
					blackTransparent16: 'hsl(var(--common-black)/ 16%)',
					blackTransparent24: 'hsl(var(--common-black)/ 24%)',
					blackTransparent32: 'hsl(var(--common-black)/ 32%)',
					blackTransparent48: 'hsl(var(--common-black)/ 48%)',
					white: 'hsl(var(--common-white))',
					whiteTransparent8: 'hsl(var(--common-white)/ 8%)',
					whiteTransparent12: 'hsl(var(--common-white)/ 12%)',
					whiteTransparent16: 'hsl(var(--common-white)/ 16%)',
					whiteTransparent24: 'hsl(var(--common-white)/ 24%)',
					whiteTransparent32: 'hsl(var(--common-white)/ 32%)',
					whiteTransparent48: 'hsl(var(--common-white)/ 48%)',
				},
			},
			fontFamily: {
				sans: ['NunitoSans', ...defaultTheme.fontFamily.sans],
			},
		},
	},
	plugins: [require('tailwindcss-animate')],
};
